/**
 * Banco de questoes. As respostas corretas nunca saem deste modulo.
 * O cliente recebe apenas enunciado, tipo e alternativas.
 */

const TESTS = [
  {
    id: "sequences",
    icon: "123",
    iconClass: "seq",
    title: "Sequências Numéricas",
    description: "Identifique o padrão e complete a série.",
    questions: [
      {
        id: "seq-1",
        text: "Qual número vem a seguir?",
        type: "sequence",
        body: { items: ["2", "4", "8", "16", "?"] },
        options: ["24", "32", "30", "20"],
        correct: 1,
        difficulty: 1,
      },
      {
        id: "seq-2",
        text: "Qual número vem a seguir?",
        type: "sequence",
        body: { items: ["3", "6", "12", "21", "33", "?"] },
        options: ["45", "48", "51", "42"],
        correct: 1,
        difficulty: 2,
      },
      {
        id: "seq-3",
        text: "Qual número vem a seguir?",
        type: "sequence",
        body: { items: ["1", "1", "2", "3", "5", "8", "?"] },
        options: ["11", "13", "12", "10"],
        correct: 1,
        difficulty: 1,
      },
      {
        id: "seq-4",
        text: "Qual número vem a seguir?",
        type: "sequence",
        body: { items: ["81", "27", "9", "3", "?"] },
        options: ["0", "1", "2", "6"],
        correct: 1,
        difficulty: 1,
      },
      {
        id: "seq-5",
        text: "Qual número vem a seguir?",
        type: "sequence",
        body: { items: ["5", "10", "20", "40", "?"] },
        options: ["60", "70", "80", "90"],
        correct: 2,
        difficulty: 1,
      },
      {
        id: "seq-6",
        text: "Qual número vem a seguir?",
        type: "sequence",
        body: { items: ["2", "3", "5", "8", "12", "?"] },
        options: ["16", "17", "18", "15"],
        correct: 1,
        difficulty: 2,
      },
      {
        id: "seq-7",
        text: "Qual número vem a seguir?",
        type: "sequence",
        body: { items: ["2", "6", "12", "20", "30", "?"] },
        options: ["40", "42", "44", "38"],
        correct: 1,
        difficulty: 2,
      },
    ],
  },
  {
    id: "logic",
    icon: "LOG",
    iconClass: "logic",
    title: "Raciocínio Lógico",
    description: "Deduzir conclusões a partir de premissas.",
    questions: [
      {
        id: "log-1",
        text: "Todos os gatos são mamíferos. Mimi é um gato. Logo:",
        type: "text",
        body: { text: "O que podemos concluir?" },
        options: [
          "Mimi não é mamífero",
          "Mimi é mamífero",
          "Alguns mamíferos não são gatos",
          "Mimi é um cachorro",
        ],
        correct: 1,
        difficulty: 1,
      },
      {
        id: "log-2",
        text: "Se chove, a rua fica molhada. A rua está seca. Logo:",
        type: "text",
        body: { text: "O que é verdadeiro?" },
        options: [
          "Está chovendo",
          "Não está chovendo",
          "A rua sempre fica seca",
          "Não podemos saber",
        ],
        correct: 1,
        difficulty: 2,
      },
      {
        id: "log-3",
        text: "Ana é mais alta que Bruno. Bruno é mais alto que Carla. Quem é o mais baixo?",
        type: "text",
        body: { text: "Escolha a resposta correta:" },
        options: ["Ana", "Bruno", "Carla", "Ana e Carla"],
        correct: 2,
        difficulty: 1,
      },
      {
        id: "log-4",
        text: "Nenhum peixe voa. Alguns animais que nadam bem são peixes. Logo:",
        type: "text",
        body: { text: "Qual afirmação é correta?" },
        options: [
          "Todos os nadadores voam",
          "Alguns nadadores não voam",
          "Peixes nao nadam",
          "Animais que nadam voam",
        ],
        correct: 1,
        difficulty: 2,
      },
      {
        id: "log-5",
        text: "Se todo A é B e algum B é C, então:",
        type: "text",
        body: { text: "Qual conclusão é necessariamente verdadeira?" },
        options: [
          "Todo A é C",
          "Nenhum A é C",
          "Algum A é C",
          "Não se pode afirmar que algum A é C",
        ],
        correct: 3,
        difficulty: 3,
      },
      {
        id: "log-6",
        text: "Em uma fila, Pedro está à frente de Lia. Lia está atrás de Caio. Caio está atrás de Pedro. Quem está no meio?",
        type: "text",
        body: { text: "Deduz a ordem da fila (frente para trás):" },
        options: ["Lia", "Caio", "Pedro", "Impossível saber"],
        correct: 1,
        difficulty: 2,
      },
      {
        id: "log-7",
        text: "Cinco máquinas fazem 5 peças em 5 minutos. Quanto tempo 100 máquinas levam para 100 peças?",
        type: "text",
        body: { text: "Considere o mesmo ritmo por máquina:" },
        options: ["100 min", "20 min", "5 min", "1 min"],
        correct: 2,
        difficulty: 3,
      },
    ],
  },
  {
    id: "visual",
    icon: "VIS",
    iconClass: "visual",
    title: "Padrões Visuais",
    description: "Complete matrizes de formas e cores.",
    questions: [
      {
        id: "vis-1",
        text: "Qual forma completa o padrão?",
        type: "pattern",
        body: { cells: ["\u25CF", "\u25CB", "\u25CF", "\u25CB", "\u25CF", "?", "\u25CF", "\u25CB", "\u25CF"] },
        options: ["\u25CF", "\u25CB", "\u25B3", "\u25A1"],
        correct: 1,
        difficulty: 1,
      },
      {
        id: "vis-2",
        text: "Qual número falta na matriz?",
        type: "pattern",
        body: { cells: ["1", "2", "3", "4", "5", "?", "7", "8", "9"] },
        options: ["5", "6", "10", "0"],
        correct: 1,
        difficulty: 1,
      },
      {
        id: "vis-3",
        text: "Qual símbolo completa a sequência?",
        type: "pattern",
        body: { cells: ["\u25B2", "\u25B2", "\u25BC", "\u25B2", "\u25B2", "?", "\u25B2", "\u25B2", "\u25BC"] },
        options: ["\u25B2", "\u25BC", "\u25CF", "\u25A0"],
        correct: 1,
        difficulty: 2,
      },
      {
        id: "vis-4",
        text: "Qual letra segue o padrao?",
        type: "pattern",
        body: { cells: ["A", "C", "E", "G", "?", "K", "M", "O", "Q"] },
        options: ["H", "I", "J", "F"],
        correct: 1,
        difficulty: 2,
      },
      {
        id: "vis-5",
        text: "Qual forma completa a matriz?",
        type: "pattern",
        body: { cells: ["\u25A0", "\u25A0", "\u25A1", "\u25A0", "?", "\u25A1", "\u25A0", "\u25A0", "\u25A1"] },
        options: ["\u25A0", "\u25A1", "\u25CB", "\u25B2"],
        correct: 0,
        difficulty: 2,
      },
      {
        id: "vis-6",
        text: "Qual número completa a rotação da linha?",
        type: "pattern",
        body: { cells: ["2", "4", "8", "3", "6", "12", "4", "8", "?"] },
        options: ["10", "12", "16", "20"],
        correct: 2,
        difficulty: 3,
      },
      {
        id: "vis-7",
        text: "Qual símbolo falta para manter a simetria?",
        type: "pattern",
        body: { cells: ["\u25C7", "\u25C6", "\u25C7", "\u25C6", "?", "\u25C6", "\u25C7", "\u25C6", "\u25C7"] },
        options: ["\u25C6", "\u25C7", "\u25CB", "\u25A0"],
        correct: 1,
        difficulty: 2,
      },
    ],
  },
  {
    id: "verbal",
    icon: "VER",
    iconClass: "verbal",
    title: "Analogias Verbais",
    description: "Relações entre palavras e conceitos.",
    questions: [
      {
        id: "ver-1",
        text: "Médico está para hospital assim como professor está para:",
        type: "text",
        body: { text: "Complete a analogia:" },
        options: ["Livro", "Escola", "Aluno", "Caneta"],
        correct: 1,
        difficulty: 1,
      },
      {
        id: "ver-2",
        text: "Pássaro está para voar assim como peixe está para:",
        type: "text",
        body: { text: "Complete a analogia:" },
        options: ["Água", "Nadar", "Escama", "Mar"],
        correct: 1,
        difficulty: 1,
      },
      {
        id: "ver-3",
        text: "Quente está para frio assim como dia está para:",
        type: "text",
        body: { text: "Complete a analogia:" },
        options: ["Sol", "Noite", "Luz", "Hora"],
        correct: 1,
        difficulty: 1,
      },
      {
        id: "ver-4",
        text: "Pintor está para tela assim como escritor está para:",
        type: "text",
        body: { text: "Complete a analogia:" },
        options: ["Caneta", "Página", "História", "Livro"],
        correct: 1,
        difficulty: 2,
      },
      {
        id: "ver-5",
        text: "Chave está para fechadura assim como senha está para:",
        type: "text",
        body: { text: "Complete a analogia:" },
        options: ["Computador", "Acesso", "Teclado", "Usuário"],
        correct: 1,
        difficulty: 2,
      },
      {
        id: "ver-6",
        text: "Raiz está para árvore assim como alicerce está para:",
        type: "text",
        body: { text: "Complete a analogia:" },
        options: ["Tijolo", "Casa", "Telhado", "Porta"],
        correct: 1,
        difficulty: 2,
      },
      {
        id: "ver-7",
        text: "Escasso está para abundante assim como rígido está para:",
        type: "text",
        body: { text: "Complete a analogia:" },
        options: ["Duro", "Flexível", "Forte", "Estavel"],
        correct: 1,
        difficulty: 3,
      },
    ],
  },
  {
    id: "math",
    icon: "MAT",
    iconClass: "math",
    title: "Raciocínio Matemático",
    description: "Problemas numéricos e proporções.",
    questions: [
      {
        id: "mat-1",
        text: "Um relógio atrasa 5 minutos por hora. Quantos minutos atrasa em 6 horas?",
        type: "text",
        body: { text: "Calcule:" },
        options: ["25 min", "30 min", "35 min", "40 min"],
        correct: 1,
        difficulty: 1,
      },
      {
        id: "mat-2",
        text: "Se 3 trabalhadores fazem um muro em 12 dias, quantos dias levam 4 trabalhadores?",
        type: "text",
        body: { text: "Considere a mesma produtividade:" },
        options: ["8 dias", "9 dias", "10 dias", "16 dias"],
        correct: 1,
        difficulty: 2,
      },
      {
        id: "mat-3",
        text: "Qual é 25% de 240?",
        type: "text",
        body: { text: "Calcule:" },
        options: ["50", "55", "60", "65"],
        correct: 2,
        difficulty: 1,
      },
      {
        id: "mat-4",
        text: "Um número dividido por 4 dá 17. Qual é esse número?",
        type: "text",
        body: { text: "Encontre o número:" },
        options: ["64", "68", "72", "76"],
        correct: 1,
        difficulty: 1,
      },
      {
        id: "mat-5",
        text: "Um produto de R$ 80 sobe 25% e depois cai 20%. Qual o preço final?",
        type: "text",
        body: { text: "Calcule:" },
        options: ["R$ 76", "R$ 80", "R$ 84", "R$ 88"],
        correct: 1,
        difficulty: 2,
      },
      {
        id: "mat-6",
        text: "A média de 4 números é 18. Três deles são 12, 20 e 16. Qual é o quarto?",
        type: "text",
        body: { text: "Encontre o número:" },
        options: ["22", "24", "26", "28"],
        correct: 1,
        difficulty: 2,
      },
      {
        id: "mat-7",
        text: "Se 2^x = 32, qual e o valor de x?",
        type: "text",
        body: { text: "Calcule:" },
        options: ["4", "5", "6", "16"],
        correct: 1,
        difficulty: 2,
      },
    ],
  },
];

function allQuestions() {
  return TESTS.flatMap((test) =>
    test.questions.map((q) => ({ ...q, testId: test.id, testTitle: test.title }))
  );
}

function getPublicCatalog() {
  return {
    estimatedMinutes: 18,
    testCount: TESTS.length,
    questionCount: allQuestions().length,
    tests: TESTS.map((test) => ({
      id: test.id,
      icon: test.icon,
      iconClass: test.iconClass,
      title: test.title,
      description: test.description,
      questionCount: test.questions.length,
      questions: test.questions.map((q) => ({
        id: q.id,
        text: q.text,
        type: q.type,
        body: q.body,
        options: q.options,
      })),
    })),
  };
}

function getQuestionMap() {
  const map = new Map();
  for (const q of allQuestions()) {
    map.set(q.id, q);
  }
  return map;
}

export {
  TESTS,
  allQuestions,
  getPublicCatalog,
  getQuestionMap,
};
